import { Noun } from "./types";

export const NOUNS: Noun[] = [
  { english: "man", german: "Mann", article: "der" },
  { english: "woman", german: "Frau", article: "die" },
  { english: "child", german: "Kind", article: "das" },
  { english: "house", german: "Haus", article: "das" },
  { english: "dog", german: "Hund", article: "der" },
  { english: "cat", german: "Katze", article: "die" },
  { english: "apple", german: "Apfel", article: "der" },
  { english: "bread", german: "Brot", article: "das" },
  { english: "book", german: "Buch", article: "das" },
  { english: "car", german: "Auto", article: "das" },
  { english: "street", german: "Straße", article: "die" },
  { english: "city", german: "Stadt", article: "die" },
  { english: "school", german: "Schule", article: "die" },
  { english: "teacher", german: "Lehrer", article: "der" },
  { english: "sun", german: "Sonne", article: "die" },
  { english: "moon", german: "Mond", article: "der" },
  { english: "water", german: "Wasser", article: "das" },
  { english: "time", german: "Zeit", article: "die" },
  { english: "day", german: "Tag", article: "der" },
  { english: "night", german: "Nacht", article: "die" },
  { english: "friend", german: "Freund", article: "der" },
  { english: "family", german: "Familie", article: "die" },
  { english: "money", german: "Geld", article: "das" },
  { english: "music", german: "Musik", article: "die" },
  { english: "food", german: "Essen", article: "das" },
];
